In [2]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [4]:
#비어있는 5x3 텐서 생성
x = torch.empty(5, 3)
print(x)

tensor([[9.1837e-39, 4.6837e-39, 9.9184e-39],
        [9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 1.0745e-38]])


Construct a randomly initialized matrix:



In [5]:
#무작위 5x3 텐서 생성
x = torch.rand(5, 3)
print(x)

tensor([[0.7207, 0.0996, 0.0209],
        [0.3389, 0.6767, 0.6474],
        [0.9771, 0.0180, 0.2566],
        [0.1743, 0.5480, 0.8122],
        [0.3158, 0.5102, 0.9052]])


Construct a matrix filled zeros and of dtype long:



In [6]:
#0으로 구성된 5x3 텐서 생성, 데이터 타입 지정(https://pytorch.org/docs/stable/tensors.html)
#torch.long dtype은 64-bit integer
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [7]:
#직접 값을 입력
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [5]:
#직접 입력 후 dtype 설정
x=torch.tensor([5.5,3],dtype=torch.long)
print(x)

tensor([5, 3])


In [16]:
xx = x.new_ones(10, 3, dtype=torch.double)

In [18]:
x

tensor([[ 1.0911, -0.4669, -0.5732],
        [ 0.2194,  2.5995, -1.0283],
        [ 0.1046,  0.0519,  1.2441],
        [ 0.6739, -0.1061,  1.3448],
        [-0.4917,  0.2341,  1.9214]])

In [21]:
#new_ones(size, dtype=None, device=None, requires_grad=False) → Tensor
#Returns a Tensor of size size filled with 1. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.

#입력된 사이즈에 해당하는 1로 채워진 텐서를 반환함.

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

#데이터 타입을 덮어 쓸 수 있음.
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.2451, -0.5715, -0.4774],
        [-1.3265, -0.3784, -0.6682],
        [ 0.3211,  0.3665, -0.9230],
        [-1.2857,  0.4446, -0.9346],
        [ 0.0040,  1.2530, -0.9899]])


Get its size:



In [9]:
#토치 텐서의 사이즈를 반환하는 코드

print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [23]:
#5x3 텐서끼리의 합
# 사이즈가 다르면 연산이 안됨
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.8843, -0.1061, -0.3403],
        [-0.7251, -0.2708, -0.1428],
        [ 0.5178,  0.3906, -0.6833],
        [-0.8521,  0.5810, -0.8617],
        [ 0.2172,  1.4664, -0.5177]])


Addition: syntax 2



In [11]:
#동일한 작업을 수행하는 torch.add 메서드
print(torch.add(x, y))

tensor([[ 1.6248,  0.2869,  0.3590],
        [ 0.3149,  3.0290, -0.5150],
        [ 0.4330,  0.1292,  2.1894],
        [ 0.7088,  0.6277,  2.1950],
        [ 0.3090,  0.6849,  2.9014]])


Addition: providing an output tensor as argument



In [13]:
#비어 있는 텐서 형성
result = torch.empty(5, 3)
result

tensor([[1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38],
        [9.5510e-39, 8.7245e-39, 1.0194e-38],
        [9.0919e-39, 8.7245e-39, 1.0194e-38]])

In [14]:
# 연산 결과물을 result에 저장
torch.add(x, y, out=result)
print(result)

tensor([[ 1.6248,  0.2869,  0.3590],
        [ 0.3149,  3.0290, -0.5150],
        [ 0.4330,  0.1292,  2.1894],
        [ 0.7088,  0.6277,  2.1950],
        [ 0.3090,  0.6849,  2.9014]])


Addition: in-place

In [13]:
#y에 x를 더함
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.8109,  1.3324,  2.3483],
        [ 0.8321, -0.3524,  0.4492],
        [ 2.0152, -1.0117,  0.5119],
        [ 1.4217,  3.2517,  0.4843],
        [ 0.2498, -0.8855, -1.6932]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [ ]:
# 기존 텐서와 대치하는 작업은 "_(언더스코어)"로 이루어짐. 

In [28]:
print(y,x)
x.copy_(y)
print(x)

tensor([[0.6392, 0.4654, 0.1371],
        [0.6014, 0.1076, 0.5253],
        [0.1967, 0.0242, 0.2398],
        [0.4337, 0.1364, 0.0729],
        [0.2132, 0.2135, 0.4722]]) tensor([[ 1.2451, -0.5715, -0.4774],
        [-1.3265, -0.3784, -0.6682],
        [ 0.3211,  0.3665, -0.9230],
        [-1.2857,  0.4446, -0.9346],
        [ 0.0040,  1.2530, -0.9899]])
tensor([[0.6392, 0.4654, 0.1371],
        [0.6014, 0.1076, 0.5253],
        [0.1967, 0.0242, 0.2398],
        [0.4337, 0.1364, 0.0729],
        [0.2132, 0.2135, 0.4722]])


In [29]:
#넘파이 방식의 인덱싱을 모두 사용할 수 있음
print(x[:, 1])

tensor([0.4654, 0.1076, 0.0242, 0.1364, 0.2135])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [30]:
#view(*shape) → Tensor
#Returns a new tensor with the same data as the self tensor but of a different shape.
#view 함수 : 해당 텐서로 입력된 형태의 새로운 텐서를 만들어 반환함
# size에 -1을 넣으면 나머지 dimension에서 추론해서 출력

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
#파이썬 수치값을 얻기 위해서는 .item() 메서드 사용

In [33]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2062])
0.20617206394672394


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [35]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
#.numpy() 메서드로, torch tensor를 np array로 변환 가능
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [39]:
#tensor 연산을 하면 자동으로 b 변수에도 수행됨
#반복 실행하면 값이 계속 더해지는 것을 볼 수 있음
a.add_(1)
print(a)
print(b)

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [20]:
#반대로, Numpy array를 Torch Tensor로 변환

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!